<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>

<option value="">-----SELECT-----</option>
<option value="THE VAISH CO-OPERATIVE COMMERCIAL BANK LTD">THE VAISH CO-OPERATIVE COMMERCIAL BANK LTD</option>
<option value="ABN AMRO BANK">ABN AMRO BANK</option>
<option value="ANDHRA BANK">ANDHRA BANK</option>
<option value="Karnataka Bank Ltd">Karnataka Bank Ltd</option>
<option value="PRIME CO-OPERATIVE BANK LTD.">PRIME CO-OPERATIVE BANK LTD.</option>
<option value="RAJKOT NAGARIK SAHAKARI BANK LTD">RAJKOT NAGARIK SAHAKARI BANK LTD</option>
<option value="THE JAMMU AND KASHMIR BANK">THE JAMMU AND KASHMIR BANK</option>
<option value="THE CATHOLIC SYRIAN BANK LTD">THE CATHOLIC SYRIAN BANK LTD</option>
<option value="THE SOUTH INDIAN BANK LTD">THE SOUTH INDIAN BANK LTD</option>
<option value="TAMILNADU MERCANTILE BANK LTD">TAMILNADU MERCANTILE BANK LTD</option>
<option value="THE VELLORE DIST CENTRAL COOP BANK LTD">THE VELLORE DIST CENTRAL COOP BANK LTD</option>
<option value="TNMBL">TNMBL</option>
<option value="NUTAN NAGRIK SAHKARI BANK LTD">NUTAN NAGRIK SAHKARI BANK LTD</option>
<option value="CITI BANK">CITI BANK</option>
<option value="ALLAHABAD BANK">ALLAHABAD BANK</option>
<option value="THE KANGRA CO-OPERATIVE BANK LIMITED">THE KANGRA CO-OPERATIVE BANK LIMITED</option>
<option value="KNGRA CO-OPERATIVE BANK LTD.">KNGRA CO-OPERATIVE BANK LTD.</option>
<option value="CENTRAL BANK OF INDIA">CENTRAL BANK OF INDIA</option>
<option value="PANJAB AND SIND BANK">PANJAB AND SIND BANK</option>
<option value="STATE BANK OF INDORE">STATE BANK OF INDORE</option>
<option value="HDFC BANK">HDFC BANK</option>
<option value="BANK OF PUNJAB LTD.">BANK OF PUNJAB LTD.</option>
<option value="STATE BANK OF SAURASHTRA">STATE BANK OF SAURASHTRA</option>
<option value="BARCLAYS BANK PLC">BARCLAYS BANK PLC</option>
<option value="STATE BANK OF PUNJAB">STATE BANK OF PUNJAB</option>
<option value="STATE BANK OF INDIA">STATE BANK OF INDIA</option>
<option value="KARUR VYSYA BANK">KARUR VYSYA BANK</option>
<option value="STATE BANK OF BIKANER AND JAIPUR">STATE BANK OF BIKANER &amp; JAIPUR</option>
<option value="UCO BANK">UCO BANK</option>
<option value="PUNJAB NATIONAL BANK">PUNJAB NATIONAL BANK</option>
<option value="THE HONGKONG AND SHANGHAI">THE HONGKONG AND SHANGHAI</option>
<option value="HSBC BANK">HSBC BANK</option>
<option value="DEVELOPMENT CREDIT BANK LTD.">DEVELOPMENT CREDIT BANK LTD.</option>
<option value="THE BANK OF NOVA SCOTIA">THE BANK OF NOVA SCOTIA</option>
<option value="DEUTSCHE BANK">DEUTSCHE BANK</option>
<option value="VIJAYA BANK">VIJAYA BANK</option>
<option value="CANARA BANK">CANARA BANK</option>
<option value="THE JAMMU AND KASHMIR BANK LTD.">THE JAMMU &amp; KASHMIR BANK LTD.</option>
<option value="STATE BANK OF MYSORE">STATE BANK OF MYSORE</option>
<option value="ING VYSYA BANK">ING VYSYA BANK</option>
<option value="STATE BANK OF HYDERABAD">STATE BANK OF HYDERABAD</option>
<option value="INDIAN OVERSEAS BANK">INDIAN OVERSEAS BANK</option>
<option value="CITY BANK">CITY BANK</option>
<option value="SBBJ">SBBJ</option>
<option value="ABUDHABI COMM.">ABUDHABI COMM.</option>
<option value="CENTURION BANK">CENTURION BANK</option>
<option value="PUNJAB AND SIND BANK">PUNJAB &amp; SIND BANK</option>
<option value="AXIS BANK LTD">AXIS BANK LTD</option>
<option value="MAHINDRA BANK LTD">MAHINDRA BANK LTD</option>
<option value="UTI BANK">UTI BANK</option>
<option value="Bank of Mahareshtra">Bank of Mahareshtra</option>
<option value="THE BHARAT CO-OP BANK LTD.">THE BHARAT CO-OP BANK LTD.</option>
<option value="INDUSLND BANK">INDUSLND BANK</option>
<option value="BOMBAY MERCANTILE CO-OP BANK">BOMBAY MERCANTILE CO-OP BANK</option>
<option value="JANAKALYAN SAHAKARI BANK LTD.">JANAKALYAN SAHAKARI BANK LTD.</option>
<option value="KOTAK MAHINDRA BANK">KOTAK MAHINDRA BANK</option>
<option value="UNION BANK OF INDIA">UNION BANK OF INDIA</option>
<option value="ICICI BANK LTD">ICICI BANK LTD</option>
<option value="CORPORATION BANK">CORPORATION BANK</option>
<option value="Centurion Bank of Punjab Ltd.">Centurion Bank of Punjab Ltd.</option>
<option value="INDIAN BANK">INDIAN BANK</option>
<option value="J AND K BANK LTD">J &amp; K BANK LTD</option>
<option value="THE NAINITAL BANK">THE NAINITAL BANK</option>
<option value="MAHAMEDHA URBAN CO-OPERATIVE BANK">MAHAMEDHA URBAN CO-OPERATIVE BANK</option>
<option value="MAHAMEDHA URBAN CO-OPE BANK">MAHAMEDHA URBAN CO-OPE BANK</option>
<option value="Jain Co-Operative Bank">Jain Co-Operative Bank</option>
<option value="INDIAN BANK OF AHMEDABAD">INDIAN BANK OF AHMEDABAD</option>
<option value="HSBC">HSBC</option>
<option value="DENA BANK">DENA BANK</option>
<option value="THE SARASWAT BANK">THE SARASWAT BANK</option>
<option value="CITY UNION BANK">CITY UNION BANK</option>
<option value="HONGKONG AND SANGHAI BANK CO. LTD.">HONGKONG &amp; SANGHAI BANK CO. LTD.</option>
<option value="HONGKONG AND SHANGHAI BANK">HONGKONG &amp; SHANGHAI BANK</option>
<option value="BANK OF INDIA">BANK OF INDIA</option>
<option value="IDBI BANK">IDBI BANK</option>
<option value="THE FEDERAL BANK LIMITED">THE FEDERAL BANK LIMITED</option>
<option value="PEN CO-OP URBEN BANK">PEN CO-OP URBEN BANK</option>
<option value="UBI">UBI</option>
<option value="ABN Amro Bank">ABN Amro Bank</option>
<option value="SOUTH INDIAN BANK LTD">SOUTH INDIAN BANK LTD</option>
<option value="THE BANK OF RAJASTHAN LTD.">THE BANK OF RAJASTHAN LTD.</option>
<option value="DEVELOPMENT COMMERCE BANK">DEVELOPMENT COMMERCE BANK</option>
<option value="BARCLAYS BANK">BARCLAYS BANK</option>
<option value="BANK OF NOVA SCOTIA">BANK OF NOVA SCOTIA</option>
<option value="AMERICAN EXPRESS BANK LTD.">AMERICAN EXPRESS BANK LTD.</option>
<option value="THE KARUR VYSYA BANK LTD.">THE KARUR VYSYA BANK LTD.</option>
<option value="ORIENTAL BANK OF COMMERCE">ORIENTAL BANK OF COMMERCE</option>
<option value="SYNDICATE BANK">SYNDICATE BANK</option>
<option value="AXIS BANK">AXIS BANK</option>
<option value="THE DHANALAKSHMI BANK LTD">THE DHANALAKSHMI BANK LTD</option>
<option value="NEW INDIA CO-OP. BANK LTD.">NEW INDIA CO-OP. BANK LTD.</option>
<option value="HDFC BANK LTD.">HDFC BANK LTD.</option>
<option value="THE MEMON CO-OP. BANK LTD.">THE MEMON CO-OP. BANK LTD.</option>
<option value="THE COSMOS CO-OP. BANK LTD.">THE COSMOS CO-OP. BANK LTD.</option>
<option value="NKGSB CO-OP BANK">NKGSB CO-OP BANK</option>
<option value="THE GREATER BOMBAY CO-OP BANK LTD.">THE GREATER BOMBAY CO-OP BANK LTD.</option>
<option value="BANK OF MAHARASHTRA">BANK OF MAHARASHTRA</option>
<option value="BMC BANK LTD">BMC BANK LTD</option>
<option value="the greater bombay co-op ltd">the greater bombay co-op ltd</option>
<option value="CITIZEN CREDIT CO-OP-BANK LTD.">CITIZEN CREDIT CO-OP-BANK LTD.</option>
<option value="THE MAHANAGAR CO-OP. BANK LTD">THE MAHANAGAR CO-OP. BANK LTD</option>
<option value="SARCO">SARCO</option>
<option value="PANJAB NATIONAL BANK">PANJAB NATIONAL BANK</option>
<option value="The Vysya Bank Ltd.">The Vysya Bank Ltd.</option>
<option value="THE ING VYSYA BANK LTD">THE ING VYSYA BANK LTD</option>
<option value="THE LAKSHMI VILAS BANK LTD">THE LAKSHMI VILAS BANK LTD</option>
<option value="KARNATKA BANK LTD">KARNATKA BANK LTD</option>
<option value="YES BANK">YES BANK</option>
<option value="APNA SAHAKAR BANK LTD.">APNA SAHAKAR BANK LTD.</option>
<option value="JAMMU &amp; KASHMIR BANK LTD">JAMMU &amp; KASHMIR BANK LTD</option>
<option value="BARDAYS">BARDAYS</option>
<option value="FEDERAL BANK">FEDERAL BANK</option>
<option value="UNITED BANK OF INDIA">UNITED BANK OF INDIA</option>
<option value="THE SARASWAT CO-OP. BANK LTD.">THE SARASWAT CO-OP. BANK LTD.</option>
<option value="MODEL CO-OP BANK LTD.">MODEL CO-OP BANK LTD.</option>
<option value="PUNE &amp; MAHA CO-OP BANK LTD.">PUNE &amp; MAHA CO-OP BANK LTD.</option>
<option value="STATE BANK OF BIKANER">STATE BANK OF BIKANER</option>
<option value="THE RATNAKAR BANK LTD.">THE RATNAKAR BANK LTD.</option>
<option value="STATE BANK OF TRAVANCORE">STATE BANK OF TRAVANCORE</option>
<option value="THE SHAMRAO VITHAL BANK">THE SHAMRAO VITHAL BANK</option>
<option value="NAVAS SCOTIA BANK">NAVAS SCOTIA BANK</option>
<option value="the pen co.op. urban bank">the pen co.op. urban bank</option>
<option value="THE THANE JANATA SAHAKARI BANK">THE THANE JANATA SAHAKARI BANK</option>
<option value="ANTWERP DIAMOND BANK N.V">ANTWERP DIAMOND BANK N.V</option>
<option value="KARNATAKA BANK LTD.">KARNATAKA BANK LTD.</option>
<option value="THE KUNBI S.B. LTD.">THE KUNBI S.B. LTD.</option>
<option value="JANKALYAN SAHKARI BANK LTD.">JANKALYAN SAHKARI BANK LTD.</option>
<option value="THE GREATER BOM CO-OP BANK LTD">THE GREATER BOM CO-OP BANK LTD</option>
<option value="PUNJAB AND; MAHARASHTRA CO-OP.">PUNJAB &amp; MAHARASHTRA CO-OP.</option>
<option value="BHARAT CO-OP BANK LTD.">BHARAT CO-OP BANK LTD.</option>
<option value="S.V.C. BANK LTD.">S.V.C. BANK LTD.</option>
<option value="BASSEIN CATHLIC CO-OP BANK">BASSEIN CATHLIC CO-OP BANK</option>
<option value="THE SOUTH INDIAN BANK LTD.">THE SOUTH INDIAN BANK LTD.</option>
<option value="SURAT NATIONAL CO-OP.BANK">SURAT NATIONAL CO-OP.BANK</option>
<option value="THE MAHARASHTRA STATE CO-OP. B">THE MAHARASHTRA STATE CO-OP. B</option>
<option value="SARASWAT BANK">SARASWAT BANK</option>
<option value="ADARSH CO-OP BANK">ADARSH CO-OP BANK</option>
<option value="DEB">DEB</option>
<option value="ING VYAS BANK LTD.">ING VYAS BANK LTD.</option>
<option value="KOTAK MAHINDRA BANK LTD.">KOTAK MAHINDRA BANK LTD.</option>
<option value="AKHAND ANAND CO-OP BANK">AKHAND ANAND CO-OP BANK</option>
<option value="ING VYSYA BANK LIMITED">ING VYSYA BANK LIMITED</option>
<option value="HDFC BANK LTD">HDFC BANK LTD</option>
<option value="UTI BANK LTD.">UTI BANK LTD.</option>
<option value="INDUSIND BANK">INDUSIND BANK</option>
<option value="BANK OF RAJASTHAN">BANK OF RAJASTHAN</option>
<option value="UTI BANK LTD">UTI BANK LTD</option>
<option value="BANK OF BARODA">BANK OF BARODA</option>
<option value="THE BANK OF TOKYO MITSUB">THE BANK OF TOKYO MITSUB</option>
<option value="STATE BANK OF PATIALA">STATE BANK OF PATIALA</option>
<option value="THE BANK OF RAJASTHAN">THE BANK OF RAJASTHAN</option>
<option value="STANDARD CHARTERED BANK LTD">STANDARD CHARTERED BANK LTD</option>
<option value="SBT">SBT</option>
<option value="ABN AMRO BANK N.V.">ABN AMRO BANK N.V.</option>
<option value="THE VARACHHA CO-OP BANK LTD">THE VARACHHA CO-OP BANK LTD</option>
<option value="THE DELHI STATE CO-OPERATIVE BANK LTD">THE DELHI STATE CO-OPERATIVE BANK LTD</option>
<option value="DEVELOPMENT CREDIT BANK LTD">DEVELOPMENT CREDIT BANK LTD</option>
<option value="INDRAPRASTHA SEHKARI BANK LTD">INDRAPRASTHA SEHKARI BANK LTD</option>
<option value="TAMILNAD MERCANTILE BANK LTD">TAMILNAD MERCANTILE BANK LTD</option>
<option value="THE STATE BANK OF SAURASHTRA">THE STATE BANK OF SAURASHTRA</option>
<option value="Any Other" selected="selected">Any Other</option>
<option value="ROYAL BANK OF SCOTLAND N.V.">ROYAL BANK OF SCOTLAND N.V.</option>
</body>
</html>
